version: "3.7"

services:
  apache2:
    image: cafeechopp/apache-php:v1.0
    ports:
      - "8080:80"
      - "443:443"
    volumes: 
      - ${DOCUMENT_ROOT-./html}:/var/www/html
      - ${PHP_INI-./.config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./.config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2

    networks: 
      - backend
  mysql:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    env_file: 
      - .env
    networks: 
      - backend
    
  redis:
    image: redis:latest 
    ports:
      - "6379:6379"
    networks: 
      - backend

      
networks:
  backend:


